package chess;

import java.util.Objects;

/**
 * Represents a single square position on a chess board
 * <p>
 * Note: You can add to this class, but you may not alter
 * signature of the existing methods.
 * <p>
 * Chess positions are important for declaring the chess moves. These are used frequently in the piece classes.
 * You'll need a variable for the row and the column.
 */
public class ChessPosition {

    /**
     * This is an override generated by right-clicking the class code.
     * @return
     */
    @Override
    public String toString() {
        return "ChessPosition{" +
                "row=" + row +
                ", col=" + col +
                '}';
    }

    private final int row;
    private final int col;

    /**
     * This initialises a positon.
     * @param row
     * @param col
     */
    public ChessPosition(int row, int col) {
        this.row = row;
        this.col = col;
    }

    /**
     * @return which row this position is in
     * 1 codes for the bottom row
     */
    public int getRow() {
        return row;
    }

    /**
     * @return which column this position is in
     * 1 codes for the left row
     */
    public int getColumn() {
        return col;
    }

    /**
     * This is an override generated by right-clicking the class code.
     * @param o
     * @return
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ChessPosition that = (ChessPosition) o;
        return row == that.row && col == that.col;
    }

    /**
     * This is an override generated by right-clicking the class code.
     * @return
     */
    @Override
    public int hashCode() {
        return Objects.hash(row, col);
    }
}
